### ISSUE TITLE
Exception launching Jetty Runner Plugin

### ISSUE THREAD

**Issue by gparello** [guikeller/jetty-runner#14]
Number of Path(s) and Folder(s) must match: /cup / 
java.lang.IllegalArgumentException: Number of Path(s) and Folder(s) must match: /cup / 
	at com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine.getWebAppPath(JettyRunnerCommandLine.java:134)
	at com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine.createJavaParameters(JettyRunnerCommandLine.java:71)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:35)
	at com.intellij.execution.configurations.JavaCommandLineState.createCommandLine(JavaCommandLineState.java:53)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:43)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:25)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.github.guikeller.jettyrunner.runner.JettyProgramRunner.doExecute(JettyProgramRunner.java:47)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:219)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:146)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:186)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by guikeller** [comment]
Hi gparello,

The error message from the exception says the following below: 
*The number of Path(s) and Folder(s) must match: /cup /*

Your conf must be similar to the following below for multiple contexts to work:
<hr>
**Path:**
/cup,/

**WebApp Folder:**
/Users/gparello/Documents/IdeaProjects/cup/src/main/webapp,/Users/gparello/Documents/IdeaProjects/root/src/main/webapp

**Classes Folder:**
/Users/gparello/Documents/IdeaProjects/cup/target/classes,/Users/gparello/Documents/IdeaProjects/root/target/classes
<hr>

For more info about it have a look here - line 105 and line 141:
https://github.com/guikeller/jetty-runner/blob/master/src/main/java/com/github/guikeller/jettyrunner/model/JettyRunnerCommandLine.java

Otherwise, if this is too confusing try and use a Jetty XML configuration file instead.
http://www.eclipse.org/jetty/documentation/9.2.6.v20141205/configuring-specific-webapp-deployment.html

<hr>

If the problem persists please provide the following info below:
1) A screenshot of your conf. 
2) JVM version 
3) Plugin Version
4) Logs
5) Steps to replicate the bug 

Kind regards,
Gui

**Comment by guikeller** [comment]
It has been 10 (ten) days without any feedback on this.
Closing the issue; "won't fix" as it works as documented in the issue.
