### ISSUE TITLE
NullPointerException opening Jetty Runner configuration panel

### ISSUE THREAD

**Issue by chalkos** [guikeller/jetty-runner#19]
Intellij Community v14.1.5

```
$ java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

I installed the plugin and restarted Intellij. When Intellij was done restarting I opened the "Edit configurations..." and this error happens every time the "Jetty Runner" configuration panel appears.

Steps to reproduce:
1. create a new project with:
```mvn archetype:generate -DarchetypeArtifactId=jersey-quickstart-grizzly2 -DarchetypeGroupId=org.glassfish.jersey.archetypes -DinteractiveMode=false -DgroupId=com.example -DartifactId=simple-service -Dpackage=com.example -DarchetypeVersion=2.2```
2. import the project in intellij
3. Menu -> Run -> Edit configurations...
4. Click on "Defaults"
5. Click on Jetty Runner
6. NullPointerException

(I don't know if an empty project also triggers an error)

```
java.lang.NullPointerException
	at com.github.guikeller.jettyrunner.ui.JettyRunnerEditor$1.execute(JettyRunnerEditor.java:141)
	at com.intellij.compiler.impl.CompileDriver$6.run(CompileDriver.java:599)
	at com.intellij.compiler.progress.CompilerTask.run(CompilerTask.java:203)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by guikeller** [comment]
Hey thanks for the bug report and sorry for the late reply - I am on holidays
As a work around build your project (make) before creating the plugin configuration.
I will work on a fix for it after my holidays, cheers!

**Comment by guikeller** [comment]
Please download the new plugin version.
It doesn't fix the issue but gives instructions on how to fix the issue.

Thanks for your help and collaboration.
