### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid classes folder

### ISSUE THREAD

**Issue by ascooper57** [guikeller/jetty-runner#21]
Invalid classes folder: 
java.lang.IllegalArgumentException: Invalid classes folder: 
	at com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine.getClassesDirectory(JettyRunnerCommandLine.java:156)
	at com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine.createJavaParameters(JettyRunnerCommandLine.java:74)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:35)
	at com.intellij.execution.configurations.JavaCommandLineState.createCommandLine(JavaCommandLineState.java:53)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:43)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:25)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.github.guikeller.jettyrunner.runner.JettyProgramRunner.doExecute(JettyProgramRunner.java:47)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:219)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:269)
	at com.intellij.openapi.project.DumbServiceImpl.access$800(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$9.run(DumbServiceImpl.java:439)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by guikeller** [comment]
Hi @ascooper57,

The "classes folder" is empty and the jetty-runner needs that to be specified to work.

See the configuration sample for an example:
http://plugins.jetbrains.com/files/7505/screenshot_15081.png

Cheers,
Gui

**Comment by ascooper57** [comment]
Hello,

The full path to the classes
is: /Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main
 The classes are in subfolders under "main". Does your plugin work in
gradle projects which are imported into Idea IntelliJ ?

Alan-Cooper-MBP:main alan_cooper$ ls -lasgF
/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main

total 0

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ./

0 drwxr-xr-x  4 staff  136 Dec 14 19:05 ../

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 com/

Alan-Cooper-MBP:main alan_cooper$ ls -lasgF
/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main/com/

total 0

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ./

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ../

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 healthbrain/

Alan-Cooper-MBP:main alan_cooper$ ls -lasgF
/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main/com/healthbrain/

total 0

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ./

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ../

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 client/

Alan-Cooper-MBP:main alan_cooper$ ls -lasgF
/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main/com/healthbrain/client/

total 0

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ./

0 drwxr-xr-x  3 staff  102 Dec 15 07:26 ../

0 drwxr-xr-x  5 staff  170 Dec 15 07:26 portal/

Alan-Cooper-MBP:main alan_cooper$ ls -lasgF
/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main/com/healthbrain/client/portal/

total 16

 0 drwxr-xr-x  5 staff   170 Dec 15 07:26 ./

 0 drwxr-xr-x  3 staff   102 Dec 15 07:26 ../

16 -rw-r--r--  1 staff  7956 Dec 15 07:26 AppConfig.class

 0 drwxr-xr-x  4 staff   136 Dec 15 07:26 controller/

 0 drwxr-xr-x  3 staff   102 Dec 15 07:26 model/

Alan S. Cooper
<http://www.linkedin.com/in/ascooper1>

**Comment by ascooper57** [comment]
This might be easier to see the file system layout:
cd /Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main
find . -name '*.class' -print
./com/healthbrain/client/portal/AppConfig.class
./com/healthbrain/client/portal/controller/MyHeightChartController.class
./com/healthbrain/client/portal/controller/StartPageController.class
./com/healthbrain/client/portal/model/Height.class

**Comment by guikeller** [comment]
Hi @ascooper57 ,

Please make sure that IntelliJ and gradle are using the same output directory.

Also, please compile / make your project using IntelliJ before creating the plugin conf. 
This way the plugin should be able to resolve the classes directory automatically.

Alternatively, you can configure the plugin manually and set the "Classes Folder" to:
"/Users/alan_cooper/Documents/GitHub/HealthBrain/hspcserver/build/classes/main".

Hope this helps and thanks for using the plugin and getting involved.

Cheers,
Gui
