### ISSUE TITLE
jetty classpath issue 

### ISSUE THREAD

**Issue by yuronew** [guikeller/jetty-runner#34]
Hello! Something weird happened today with my jetty runner instance. It cannot start web application with error:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:48)
Caused by: java.lang.NoSuchMethodError: org.eclipse.jetty.server.handler.HandlerWrapper.updateBean(Ljava/lang/Object;Ljava/lang/Object;Z)V
	at org.eclipse.jetty.server.handler.HandlerWrapper.setHandler(HandlerWrapper.java:97)
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:325)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:535)
	... 5 more

```

I suspect that default jetty.xml should be reviewed and fixed based on my preferences, but I can't find it.

**Comment by yuronew** [comment]
I found the issue, there was net.sourceforge.htmlunit:htmlunit:jar:2.20 in dependencies and it has few jetty dependecies as well

```
 +- net.sourceforge.htmlunit:htmlunit:jar:2.20:compile
[INFO] |  |  +- net.sourceforge.htmlunit:htmlunit-core-js:jar:2.17:compile
[INFO] |  |  +- xerces:xercesImpl:jar:2.11.0:compile
[INFO] |  |  +- net.sourceforge.nekohtml:nekohtml:jar:1.9.22:compile
[INFO] |  |  +- net.sourceforge.cssparser:cssparser:jar:0.9.18:compile
[INFO] |  |  |  \- org.w3c.css:sac:jar:1.3:compile
[INFO] |  |  \- org.eclipse.jetty.websocket:websocket-client:jar:9.2.15.v20160210:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-util:jar:9.2.15.v20160210:compile
[INFO] |  |     +- org.eclipse.jetty:jetty-io:jar:9.2.15.v20160210:compile
[INFO] |  |     \- org.eclipse.jetty.websocket:websocket-common:jar:9.2.15.v20160210:compile
[INFO] |  |        \- org.eclipse.jetty.websocket:websocket-api:jar:9.2.15.v20160210:compile
```

**Comment by guikeller** [comment]
Hi @yuronew 

Thanks for reporting the problem and solution.
This will def add to the project and is very much appreciated.

All the best on your project.

Best regards,
Gui
