### ISSUE TITLE
Jetty-runner cannot be launched in Intellij idea

### ISSUE THREAD

**Issue by paul-xu** [guikeller/jetty-runner#39]
Hi there, I have installed latest version of Jetty-runner (1.2.0) in Intellij idea, but I'm getting following error:

org/eclipse/jetty/runner/Runner
java.lang.NoClassDefFoundError: org/eclipse/jetty/runner/Runner
	at com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine.<clinit>(JettyRunnerCommandLine.java:30)
	at com.github.guikeller.jettyrunner.model.JettyRunnerConfiguration.getState(JettyRunnerConfiguration.java:72)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:121)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:533)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.runner.Runner PluginClassLoader[JettyRunner-GK, 1.2.0]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 31 more

JVM: 1.8.3.1
Intellij Idea: 2016.3

**Comment by guikeller** [comment]
Hi @paul-xu 

Can you please try uninstalling and installing the plugin again?

Also, make sure that you do not include any extra htmlunit / jsp / servlet jar in your classpath.
These are provided by the plugin / servlet container; and if you override these the plugin will fail to initialise the jetty server.

Let me know how you go, good luck! 👍 

Best regards,
Gui

**Comment by paul-xu** [comment]
@guikeller Hi Gui, I just uninstall/install the plugin again, but I'm getting a different error as follows:
Could not initialize class com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine
java.lang.NoClassDefFoundError: Could not initialize class com.github.guikeller.jettyrunner.model.JettyRunnerCommandLine
	at com.github.guikeller.jettyrunner.model.JettyRunnerConfiguration.getState(JettyRunnerConfiguration.java:72)
	at com.intellij.execution.runners.ExecutionEnvironment.getState(ExecutionEnvironment.java:158)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:55)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:50)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:118)
	at com.intellij.execution.impl.ExecutionManagerImpl.start(ExecutionManagerImpl.java:121)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$300(ExecutionManagerImpl.java:68)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:533)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:223)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:387)
	at com.intellij.openapi.application.TransactionGuardImpl$6.run(TransactionGuardImpl.java:318)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:417)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:401)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:843)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:679)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by guikeller** [comment]
Hi @paul-xu,

Thanks for doing that, I will check with JetBrains / IntelliJ what is going on there.

It seems that they might have changed something that is now causing this.
I will get back to you as soon as I hear back from them.

Alternatively please try a different version of IntelliJ.
I am using the plugin with no problems on:
> IntelliJ IDEA 2016.3.6
> Build #IU-163.15188.11, built on March 24, 2017
> Licensed to IDEA Jetty Runner / Gui Keller
> Subscription is active until December 12, 2017
> JRE: 1.8.0_112-release-408-b6 x86_64
> JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Thanks a lot for reporting the issue.
Cheers, Gui

**Comment by guikeller** [comment]
Hi @paul-xu 

This is what I got back from the guys there:
> It looks like the plugin jars are corrupted. It might be caused by an overly active antivirus, hardware failure or network download issue.

Please try their suggestion; let me know how you go.

Cheers,
Gui

**Comment by guikeller** [comment]
Hi @paul-xu,

Closing issue as it is an OS related issue.
If you have found any more info please send through.

Cheers,
Gui
