### ISSUE TITLE
NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z

### ISSUE THREAD

**Issue by cr22rc** [guikeller/jetty-runner#41]
mvn jetty:run  works just fine - I can use curl to get a response from my REST (rax-rs) resource.

Launching with jetty-runner I see the below

Version 1.2

IntelliJ IDEA 2017.1.4
Build #IC-171.4694.23, built on June 6, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.11.5-200.fc25.x86_64

2017-06-29 15:57:03.378:INFO:oejr.Runner:main: Runner
2017-06-29 15:57:03.515:INFO:oejs.Server:main: jetty-9.2.2.v20140723
2017-06-29 15:57:03.563:WARN:oejuc.AbstractLifeCycle:main: FAILED o.e.j.w.WebAppContext@7403c468{/webappfabricsdk,null,null}{file:/home//gitws/bc/webappfabricsdk/src/main/webapp/}: java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:380)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:347)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
2017-06-29 15:57:03.564:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.handler.ContextHandlerCollection@15bfd87[o.e.j.w.WebAppContext@7403c468{/webappfabricsdk,null,null}{file:/home/gitws/bc/webappfabricsdk/src/main/webapp/}]: java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:380)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:347)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
2017-06-29 15:57:03.564:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.handler.HandlerCollection@543e710e[org.eclipse.jetty.server.handler.ContextHandlerCollection@15bfd87[o.e.j.w.WebAppContext@7403c468{/webappfabricsdk,null,null}{file:/home/gitws/bc/webappfabricsdk/src/main/webapp/}], org.eclipse.jetty.server.handler.DefaultHandler@57f23557, org.eclipse.jetty.server.handler.RequestLogHandler@3d0f8e03]: java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:380)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:347)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
2017-06-29 15:57:03.578:INFO:oejs.ServerConnector:main: Started ServerConnector@6e38921c{HTTP/1.1}{0.0.0.0:8080}
2017-06-29 15:57:03.579:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.server.Server@64d7f7e0: java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:380)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:347)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.isAlias()Z
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:409)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:72)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:483)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:519)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:380)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:347)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536)
Connected to the target VM, address: '127.0.0.1:41419', transport: 'socket'

**Comment by guikeller** [comment]
Hi @cr22rc 

It is a classpath issue, you have another jar providing
> org.eclipse.jetty.util.resource.Resource.isAlias()

The plugin ends up using the wrong class and the error above happens.
Mark the offending jar as a "provided" dependency and you should be okay.

Let me know how you go.. 😄 

Cheers,
Gui

**Comment by cr22rc** [comment]
I finally went to using tomcat. Jetty would take forever to start up.
I never really got it to work. I stated it seemed to work running from maven on the command line same pom.xml so I not sure about the theory of classpath given that.

**Comment by guikeller** [comment]
Hi @cr22rc,

Sure, if you go with Tomcat you won't have any issues as Tomcat is not Jetty and there are no Tomcat libs on your classpath.

In regards of being a classpath issue:
> 2017-06-29 15:57:03.563:WARN:oejuc.AbstractLifeCycle:main: FAILED o.e.j.w.WebAppContext@7403c468{/webappfabricsdk,null,null}{file:/home//gitws/bc/webappfabricsdk/src/main/webapp/}: java.lang.**NoSuchMethodError**: org.eclipse.jetty.util.resource.Resource.isAlias()Z
java.lang.**NoSuchMethodError**: org.eclipse.jetty.util.resource.Resource.isAlias()Z

See Issues:  #38 - #34 - #27 - #20 
All with the same "**NoSuchMethodError**" and culprit, _classpath_.

Cheers,
Gui
