### ISSUE TITLE
Since the version 1.2.1 I got an exception

### ISSUE THREAD

**Issue by Ergul** [guikeller/jetty-runner#48]
Hi,

since I updated to the version 1.2.1 I got the following exception:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
**Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.util.TypeUtil.getLocationOfClass(Ljava/lang/Class;)Ljava/net/URI**;
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getJarFor(AnnotationConfiguration.java:642)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.getNonExcludedInitializers(AnnotationConfiguration.java:796)
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:360)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:491)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1336)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:772)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:259)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:517)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:405)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:106)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559)

Thanks in advance.

Eric

**Comment by guikeller** [comment]
Hi @Ergul 

That is a classpath issue, your project is defining a version of "org.slf4j.impl.StaticLoggerBinder" ( SL4J ) [ Logging ] that is clashing with the one required by the jetty-runner jar.

You could try to uninstall / install the plugin again to see if that fixes the problem, or have a look at the sample project to see how to avoid classpath issues.

https://github.com/guikeller/jetty-runner/wiki/Getting-Started
Best of luck with the project.

Cheers,
Gui
