### ISSUE TITLE
Exception in thread "main" java.lang.NoSuchMethodError org.eclipse.jetty.webapp.WebAppContext.getObjectFactory()

### ISSUE THREAD

**Issue by stanleyw2014** [guikeller/jetty-runner#54]
Hi,
I got stucked on an error when I was trying to start my service with jetty runner in intellij, the servlet-api version I use is 3.1.0

Exception in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.webapp.WebAppContext.getObjectFactory()Lorg/eclipse/jetty/util/DecoratedObjectFactory;
	at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:345)
	at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:479)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1337)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:742)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:399)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:518)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:559)

**Comment by guikeller** [comment]
Hi Stanley,

Can you please check your "servlet-api" declaration on your dependency manager?
Also, check for the declaration of "jetty-webapp" in it, or in one of your dependencies.

The scope of those jars should be "provided" or something similar to that.
Your classpath is currently overriding this class: **org.eclipse.jetty.webapp.WebAppContext**

As you can see it is a classpath issue:
No Such Method Error: _org.eclipse.jetty.webapp.WebAppContext_.getObjectFactory()

Let me know how you go.

Cheers,
Gui

**Comment by stanleyw2014** [comment]
Hi,Gui
Thanks for you prompt reply, I use gradle to build my project, and I use "compileOnly" to add the denpendencis, which equals to "provided" in maven, but I still got the same error above.
below is my dependencies:

compileOnly group: 'javax.servlet', name: 'javax.servlet-api', version: '3.1.0'
compileOnly group: 'org.eclipse.jetty', name: 'jetty-webapp', version: '9.4.6.v20180619'

Stanley

**Comment by guikeller** [comment]
Can you please paste the output of: $gradle dependencies
That should print your entire dependency tree and I can help you look for the culprit.

**Comment by stanleyw2014** [comment]
Hi, Gui
The problem gets solved, jetty-cdi plays the trick, I change complie to complieOnly on this denpendencies.
compileOnly group: 'org.eclipse.jetty', name: 'jetty-cdi', version:'9.3.0.M2'
