### ISSUE TITLE
Jetty-runner jetty error

### ISSUE THREAD

**Issue by jgrzebyta** [guikeller/jetty-runner#56]
Jetty runner [version 1.2.1] produces following error:
```
"C:\Program Files\Java\jdk1.8.0_172\bin\java.exe" ...
Logging to org.slf4j.impl.Log4jLoggerAdapter(org.eclipse.jetty.util.log) via org.eclipse.jetty.util.log.Slf4jLogException in thread "main" java.lang.NoSuchMethodError: org.eclipse.jetty.util.resource.Resource.close()V
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:227)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:558)

Process finished with exit code 1
```

**Comment by guikeller** [comment]
Hi @jgrzebyta 

**NoSuchMethodError**: org.eclipse.jetty.util.resource.Resource.close()V
You have a classpath issue, there is another Jetty jar present overriding the plugin's one.

There are plenty of closed issues where I explain how to fix it.
