### ISSUE TITLE
No org.apache.tomcat.InstanceManager set in ServletContext

### ISSUE THREAD

**Issue by oschina** [guikeller/jetty-runner#59]
IDEA 2018.2.3，jetty-runner 1.2.1 

when request jsp file , get this exception

Caused by: org.apache.jasper.JasperException: java.lang.IllegalStateException: No org.apache.tomcat.InstanceManager set in ServletContext
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:176)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:380)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)

what happened ?

**Comment by guikeller** [comment]
Hi @oschina 

It seems that you are using a "Tomcat" specific class in your JSP (whatever template you are using) and Jetty is not liking it. Could you please paste the whole stacktrace?

PS: it is not a plugin issue and you're more likely to get a faster answer on StackOverflow.

Thanks,
Gui

**Comment by guikeller** [comment]
See issue #63 for the solution
