### ISSUE TITLE
Upgrade to Jetty 9.4.12

### ISSUE THREAD

**Issue by emongstad** [guikeller/jetty-runner#60]
Hi

I get the following error when I run the jetty-runner with an app that transitively depends on jetty-9.4.12 libs:
2018-10-03 15:00:10,431 [app_IS_UNDEFINED][qtp1991313236-20][][][][][][][][][][][][] WARN org.eclipse.jetty.server.HttpChannel - /pin/
java.lang.NoSuchMethodError: org.eclipse.jetty.server.ResourceService.doGet(Ljavax/servlet/http/HttpServletRequest;Ljavax/servlet/http/HttpServletResponse;)V
	at org.eclipse.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:458)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:833)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:126)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

[Loaded org.eclipse.jetty.servlet.DefaultServlet from file:/C:/Users/a43152/.IntelliJIdea2018.2/config/plugins/jetty-runner/lib/jetty-runner-9.4.6.v20170531.jar]
and

[Loaded org.eclipse.jetty.server.ResourceService from file:/C:/Users/a43152/.m2/repository/org/eclipse/jetty/jetty-server/9.4.12.v20180830/jetty-server-9.4.12.v20180830.jar]

They doesn't seem to be compatible. So, is it possible to upgrade to latest jetty?

**Comment by emongstad** [comment]
This relates to #46 where plugin was upgraded to 9.4.6

**Comment by guikeller** [comment]
Hi @emongstad 

Some lib is adding "jetty-server-9.4.12.v20180830.jar" to your runtime classpath.

Then the "jetty-runner-9.4.6.v20170531.jar" (which is the one that the plugin uses) tries to use a method from the "jetty-server" jar that has the same package/class but different method signature.

Hence the: "java.lang.NoSuchMethodError: org.eclipse.jetty.server.ResourceService.doGet"
You'll have to fix your classpath to get this going..

Cheers,
Gui

**Comment by emongstad** [comment]
Hi

Yes, I'm aware that jetty 9.4.12 is added to the classpath. I can of course remove that transitive dependency, but shouldn't the plugin be up to date with Jetty changes?

**Comment by guikeller** [comment]
Hi @emongstad ,

I was looking through the changelogs and jetty-runner gets updated every three months or so.
With that in mind, I will try and update it and attend to some of the requests made by other users.

Cheers,
Gui

**Comment by guikeller** [comment]
Upgraded to 9.4.14 today! :grinning:
