### ISSUE TITLE
 No org.apache.tomcat.InstanceManager set in ServletContext

### ISSUE THREAD

**Issue by temmyg** [guikeller/jetty-runner#63]
@guikeller 

When I run Jetty Runner in IntelliJ Community, I met below error, I have tried several options, but not able to resolve it. For the same project, if I use Smart Tomcat, it runs well. My project is [here](https://github.com/temmyg/springmvc-sample2.git). Could you help? BTW, I also have reviewed previous similar issue posts, I do not think the solution you mentioned there makes sense to me.

> javax.servlet.ServletException: org.apache.jasper.JasperException: java.lang.IllegalStateException: No org.apache.tomcat.InstanceManager set in ServletContext
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
	at java.lang.Thread.run(Thread.java:748)

**Comment by guikeller** [comment]
It works here.

```
/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath "/Users/guikeller/dev/workspace/springmvc-sample2/target/classes:/Users/guikeller/.m2/repository/org/springframework/spring-webmvc/4.1.4.RELEASE/spring-webmvc-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/org/springframework/spring-beans/4.1.4.RELEASE/spring-beans-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/org/springframework/spring-context/4.1.4.RELEASE/spring-context-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/org/springframework/spring-core/4.1.4.RELEASE/spring-core-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/Users/guikeller/.m2/repository/org/springframework/spring-expression/4.1.4.RELEASE/spring-expression-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/org/springframework/spring-web/4.1.4.RELEASE/spring-web-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/org/springframework/spring-aop/4.1.4.RELEASE/spring-aop-4.1.4.RELEASE.jar:/Users/guikeller/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/guikeller/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar:/Users/guikeller/.m2/repository/taglibs/standard/1.1.2/standard-1.1.2.jar:/Users/guikeller/Library/Application Support/IdeaIC2018.3/jetty-runner/lib/jetty-runner-9.4.14.v20181114.jar" org.eclipse.jetty.runner.Runner --port 8080 --path /springmvcexample /Users/guikeller/dev/workspace/springmvc-sample2/src/main/webapp --classes /Users/guikeller/dev/workspace/springmvc-sample2/target/classes
2019-01-03 18:08:47.583:INFO::main: Logging initialized @585ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2019-01-03 18:08:47.653:INFO:oejr.Runner:main: Runner
2019-01-03 18:08:48.016:INFO:oejs.Server:main: jetty-9.4.14.v20181114; built: 2018-11-14T21:20:31.478Z; git: c4550056e785fb5665914545889f21dc136ad9e6; jvm 9+181
2019-01-03 18:08:49.146:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2019-01-03 18:08:49.147:INFO:oejs.session:main: No SessionScavenger set, using defaults
2019-01-03 18:08:49.156:INFO:oejs.session:main: node0 Scavenging every 660000ms
2019-01-03 18:08:49.645:INFO:oejshC.springmvcexample:main: Initializing Spring FrameworkServlet 'spring'
Jan 03, 2019 6:08:49 PM org.springframework.web.servlet.DispatcherServlet initServletBean
INFO: FrameworkServlet 'spring': initialization started
Jan 03, 2019 6:08:49 PM org.springframework.web.context.support.XmlWebApplicationContext prepareRefresh
INFO: Refreshing WebApplicationContext for namespace 'spring-servlet': startup date [Thu Jan 03 18:08:49 ACDT 2019]; root of context hierarchy
Jan 03, 2019 6:08:49 PM org.springframework.beans.factory.xml.XmlBeanDefinitionReader loadBeanDefinitions
INFO: Loading XML bean definitions from ServletContext resource [/WEB-INF/spring-servlet.xml]
Jan 03, 2019 6:08:50 PM org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping registerHandler
INFO: Mapped URL path [/employee-module/getAllEmployees] onto handler 'employeeController'
Jan 03, 2019 6:08:50 PM org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping registerHandler
INFO: Mapped URL path [/employee-module/getAllEmployees.*] onto handler 'employeeController'
Jan 03, 2019 6:08:50 PM org.springframework.web.servlet.mvc.annotation.DefaultAnnotationHandlerMapping registerHandler
INFO: Mapped URL path [/employee-module/getAllEmployees/] onto handler 'employeeController'
Jan 03, 2019 6:08:51 PM org.springframework.web.servlet.DispatcherServlet initServletBean
INFO: FrameworkServlet 'spring': initialization completed in 1568 ms
2019-01-03 18:08:51.246:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@475e586c{Spring Web MVC Hello World Application,/springmvcexample,file:///Users/guikeller/dev/workspace/springmvc-sample2/src/main/webapp/,AVAILABLE}{file:///Users/guikeller/dev/workspace/springmvc-sample2/src/main/webapp/}
2019-01-03 18:08:51.293:INFO:oejs.AbstractConnector:main: Started ServerConnector@2414cdbf{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2019-01-03 18:08:51.293:INFO:oejs.Server:main: Started @4358ms
Jan 03, 2019 6:09:10 PM org.springframework.web.servlet.PageNotFound noHandlerFound
WARNING: No mapping found for HTTP request with URI [/springmvcexample/] in DispatcherServlet with name 'spring'

```

When do you see that exception, what URL are you hitting?

**Comment by guikeller** [comment]
Hello @temmyg 

I was able to reproduce your issue by hitting the URL below:
http://localhost:8080/springmvcexample/index.jsp

The problem is your **web.xml** file! 

Please replace this:
```
<web-app id="WebApp_ID" version="2.4" 
	xmlns="http://java.sun.com/xml/ns/j2ee" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee 
	http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd">
```

With the content below:
```
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
	      http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
		 version="3.0">
```

It should work just fine, the exception thrown is rather misleading though.
But once again, it was a configuration issue, nothing to do with the plugin.

Good luck with the rest! Cheers

**Comment by guikeller** [comment]
That's good to know! 
Indeed and the exception thrown is also very misleading. 

Good luck on your project and please rate/review the plugin.
Cheers, Gui

**Comment by temmyg** [comment]
@guikeller 

Yes, I will rate it, overall, this plugin is good, and I like the approach it takes to launch web applications in IntelliJ. But I have another issue, I donot know if you will care about it, I posted in a new issue.
