### ISSUE TITLE
Intellij by 2017.2.7  have a error?

### ISSUE THREAD

**Issue by Marking0614** [guikeller/jetty-runner#65]
IntelliJ IDEA 2017.2.7
Plugin v.1.3.1
JVM 8

```
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.components.fields.ExpandableTextField PluginClassLoader[JettyRunner-GK, 1.3.1] com.intellij.ide.plugins.cl.PluginClassLoader@1606f9d6
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:65)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 82 more


```

Can you please help?

**Comment by guikeller** [comment]
Hi @Marking0614 ,

It seems that your Intellij version does not have the IntelliJ ExpandableTextField:
`NoClassDefFoundError: com/intellij/ui/components/fields/ExpandableTextField`

If you can please update to an newer version of IntelliJ.

Otherwise, please use the version 1.3.0 of the plugin:
https://plugins.jetbrains.com/plugin/download?rel=true&updateId=53725
You can download it from the URL above and install the plugin from disk.

Can you please let me know how you go?
Good luck, cheers! 👍
