### ISSUE TITLE
java.lang.IllegalArgumentException: No selectors

### ISSUE THREAD

**Issue by Joseph-Ryu** [guikeller/jetty-runner#67]
Im getting below here when running Intellij with Jetty Runner:
Any idea??

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -Dfile.encoding=UTF-8 -classpath "/Users/imac2/repos/intricate-solutions/bin:/Users/imac2/repos/intricate-solutions/lib/mysql-connector-java-5.1.5-bin.jar:/Users/imac2/repos/intricate-solutions/lib/standard-1.1.2.jar:/Users/imac2/repos/intricate-solutions/lib/bcmail-jdk14-138.jar:/Users/imac2/repos/intricate-solutions/lib/bcprov-jdk14-138.jar:/Users/imac2/repos/intricate-solutions/lib/yuicompressor-2.4.7.jar:/Users/imac2/repos/intricate-solutions/lib/yuicompressor-taskdef-1.0-custom.jar:/Users/imac2/repos/intricate-solutions/lib/velocity-1.7.jar:/Users/imac2/repos/intricate-solutions/lib/xmltooling-1.4.1.jar:/Users/imac2/repos/intricate-solutions/lib/commons-httpclient-3.1.jar:/Users/imac2/repos/intricate-solutions/lib/openws-1.5.1.jar:/Users/imac2/repos/intricate-solutions/lib/esapi-2.0.1.jar:/Users/imac2/repos/intricate-solutions/lib/not-yet-commons-ssl-0.3.9.jar:/Users/imac2/repos/intricate-solutions/lib/opensaml-2.6.1.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-saml2-core-1.0.3.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/xmlsec-1.5.6.jar:/Users/imac2/repos/intricate-solutions/lib/commons-lang-2.6.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/lib/tools.jar:/Users/imac2/repos/intricate-solutions/lib/slf4j-api-1.6.1.jar:/Users/imac2/repos/intricate-solutions/lib/slf4j-log4j12-1.6.1.jar:/Users/imac2/repos/intricate-solutions/lib/jstl-1.1.jar:/Users/imac2/repos/intricate-solutions/lib/commons-dbcp-1.2.2.jar:/Users/imac2/repos/intricate-solutions/lib/commons-pool-1.5.6.jar:/Users/imac2/repos/intricate-solutions/lib/dsn-1.4.4.jar:/Users/imac2/repos/intricate-solutions/lib/imap-1.4.4.jar:/Users/imac2/repos/intricate-solutions/lib/mail-1.4.4.jar:/Users/imac2/repos/intricate-solutions/lib/mailapi-1.4.4.jar:/Users/imac2/repos/intricate-solutions/lib/smtp-1.4.4.jar:/Users/imac2/repos/intricate-solutions/lib/dom4j-1.6.1.jar:/Users/imac2/repos/intricate-solutions/lib/geronimo-stax-api_1.0_spec-1.0.jar:/Users/imac2/repos/intricate-solutions/lib/xmlbeans-2.3.0.jar:/Users/imac2/repos/intricate-solutions/lib/jetty/jsp-api-2.2.jar:/Users/imac2/repos/intricate-solutions/lib/jetty/servlet-api-3.0.jar:/Applications/IntelliJ IDEA CE.app/Contents/lib/junit-4.12.jar:/Users/imac2/repos/intricate-solutions/lib/commons-fileupload-1.2.2.jar:/Users/imac2/repos/intricate-solutions/lib/antlr-2.7.6.jar:/Users/imac2/repos/intricate-solutions/lib/commons-collections-3.1.jar:/Users/imac2/repos/intricate-solutions/lib/hibernate-jpa-2.0-api-1.0.1.Final.jar:/Users/imac2/repos/intricate-solutions/lib/hibernate3.jar:/Users/imac2/repos/intricate-solutions/lib/jta-1.1.jar:/Users/imac2/repos/intricate-solutions/lib/liquibase.jar:/Users/imac2/repos/intricate-solutions/lib/com.springsource.org.aopalliance-1.0.0.jar:/Users/imac2/repos/intricate-solutions/lib/javatuples-1.2.jar:/Users/imac2/repos/intricate-solutions/lib/test/mockito-all-1.9.5.jar:/Users/imac2/repos/intricate-solutions/lib/zip4j_1.3.1.jar:/Users/imac2/repos/intricate-solutions/lib/jetty-websocket-8.1.8.jar:/Users/imac2/repos/intricate-solutions/lib/nekohtml-1.9.19.jar:/Users/imac2/repos/intricate-solutions/lib/xml-apis-1.4.01.jar:/Users/imac2/repos/intricate-solutions/lib/sac-1.3.jar:/Users/imac2/repos/intricate-solutions/lib/aspectjweaver-1.6.jar:/Users/imac2/repos/intricate-solutions/lib/stax-1.2.0.jar:/Users/imac2/repos/intricate-solutions/lib/stax-api-1.0.1.jar:/Users/imac2/repos/intricate-solutions/lib/urlrewritefilter-4.0.3.jar:/Users/imac2/repos/intricate-solutions/lib/iText-2.1.7.jar:/Users/imac2/repos/intricate-solutions/lib/jtidy-r938.jar:/Users/imac2/repos/intricate-solutions/lib/spring-aop-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-aspects-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-beans-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-context-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-context-support-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-core-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-expression-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-instrument-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-instrument-tomcat-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-jdbc-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-jms-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-orm-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-oxm-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-test-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-tx-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-web-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-webmvc-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-webmvc-portlet-4.1.1.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-acl-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-aspects-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-cas-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-config-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-core-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-crypto-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-ldap-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-openid-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-remoting-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-taglibs-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/spring-security-web-3.2.5.RELEASE.jar:/Users/imac2/repos/intricate-solutions/lib/json-20080701.jar:/Users/imac2/repos/intricate-solutions/lib/metadata-extractor-2.7.0.jar:/Users/imac2/repos/intricate-solutions/lib/xmpcore-5.1.2.jar:/Users/imac2/repos/intricate-solutions/lib/java-uuid-generator-3.1.3.jar:/Users/imac2/repos/intricate-solutions/lib/javassist-3.20.0-GA.jar:/Users/imac2/repos/intricate-solutions/lib/commons-exec-1.3.jar:/Users/imac2/repos/intricate-solutions/lib/exp4j-0.4.5.jar:/Users/imac2/repos/intricate-solutions/lib/juniversalchardet-1.0.3.jar:/Users/imac2/repos/intricate-solutions/lib/commons-csv-1.2.jar:/Users/imac2/repos/intricate-solutions/lib/jsch-0.1.54.jar:/Users/imac2/repos/intricate-solutions/lib/poi-3.10-FINAL-20140208.jar:/Users/imac2/repos/intricate-solutions/lib/poi-ooxml-3.10-FINAL-20140208.jar:/Users/imac2/repos/intricate-solutions/lib/poi-ooxml-schemas-3.10-FINAL-20140208.jar:/Users/imac2/repos/intricate-solutions/lib/htmlunit-2.26.jar:/Users/imac2/repos/intricate-solutions/lib/htmlunit-core-js-2.26.jar:/Users/imac2/repos/intricate-solutions/lib/htmlunit-driver-2.26.jar:/Users/imac2/repos/intricate-solutions/lib/httpclient-4.5.3.jar:/Users/imac2/repos/intricate-solutions/lib/httpcore-4.4.6.jar:/Users/imac2/repos/intricate-solutions/lib/httpmime-4.5.3.jar:/Users/imac2/repos/intricate-solutions/lib/cglib-nodep-3.2.4.jar:/Users/imac2/repos/intricate-solutions/lib/commons-codec-1.10.jar:/Users/imac2/repos/intricate-solutions/lib/commons-io-2.5.jar:/Users/imac2/repos/intricate-solutions/lib/commons-lang3-3.5.jar:/Users/imac2/repos/intricate-solutions/lib/commons-logging-1.2.jar:/Users/imac2/repos/intricate-solutions/lib/cssparser-0.9.22.jar:/Users/imac2/repos/intricate-solutions/lib/gson-2.8.0.jar:/Users/imac2/repos/intricate-solutions/lib/guava-21.0.jar:/Users/imac2/repos/intricate-solutions/lib/hamcrest-core-1.3.jar:/Users/imac2/repos/intricate-solutions/lib/selenium-3.4.0.jar:/Users/imac2/repos/intricate-solutions/lib/xercesImpl-2.11.0.jar:/Users/imac2/repos/intricate-solutions/lib/xalan-2.7.2.jar:/Users/imac2/repos/intricate-solutions/lib/websocket-api-9.4.3.v20170317.jar:/Users/imac2/repos/intricate-solutions/lib/websocket-client-9.4.3.v20170317.jar:/Users/imac2/repos/intricate-solutions/lib/websocket-common-9.4.3.v20170317.jar:/Users/imac2/repos/intricate-solutions/lib/neko-htmlunit-2.25.jar:/Users/imac2/repos/intricate-solutions/lib/phantomjsdriver-1.4.0.jar:/Users/imac2/repos/intricate-solutions/lib/serializer-2.7.2.jar:/Users/imac2/repos/intricate-solutions/lib/jetty-io-9.4.1.v20170120.jar:/Users/imac2/repos/intricate-solutions/lib/jetty-util-9.4.1.v20170120.jar:/Users/imac2/repos/intricate-solutions/lib/aws-java-sdk-1.11.174.jar:/Users/imac2/repos/intricate-solutions/lib/aspectjrt-1.8.2.jar:/Users/imac2/repos/intricate-solutions/lib/aws-swf-build-tools-1.1.jar:/Users/imac2/repos/intricate-solutions/lib/jackson-annotations-2.6.0.jar:/Users/imac2/repos/intricate-solutions/lib/jackson-core-2.6.7.jar:/Users/imac2/repos/intricate-solutions/lib/jackson-databind-2.6.7.1.jar:/Users/imac2/repos/intricate-solutions/lib/jackson-dataformat-cbor-2.6.7.jar:/Users/imac2/repos/intricate-solutions/lib/joda-time-2.8.1.jar:/Users/imac2/repos/intricate-solutions/lib/commons-math3-3.6.1.jar:/Users/imac2/repos/intricate-solutions/lib/HikariCP-3.2.0.jar:/Users/imac2/repos/intricate-solutions/lib/test/postgresql-42.2.1.jar:/Users/imac2/repos/intricate-solutions/lib/log4j-1.2.17.jar:/Users/imac2/repos/intricate-solutions/lib/classloader-leak-prevention-1.13.0.jar:/Users/imac2/repos/intricate-solutions/lib/pdfbox-2.0.11.jar:/Users/imac2/repos/intricate-solutions/lib/fontbox-2.0.11.jar:/Users/imac2/repos/intricate-solutions/lib/rsql-parser-2.1.0.jar:/Users/imac2/repos/intricate-solutions/lib/mssql-jdbc-7.0.0.jre8.jar:/Users/imac2/repos/intricate-solutions/lib/commons-net-3.6.jar:/Users/imac2/Library/Application Support/IdeaIC2018.3/jetty-runner/lib/jetty-runner-9.4.14.v20181114.jar" org.eclipse.jetty.runner.Runner --port 8080 --path /intricate-solutions /Users/imac2/repos/intricate-solutions/war --classes /Users/imac2/repos/intricate-solutions/bin
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
java.lang.IllegalArgumentException: No selectors
	at org.eclipse.jetty.io.SelectorManager.<init>(SelectorManager.java:64)
	at org.eclipse.jetty.server.ServerConnector$ServerConnectorManager.<init>(ServerConnector.java:532)
	at org.eclipse.jetty.server.ServerConnector.newSelectorManager(ServerConnector.java:227)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:220)
	at org.eclipse.jetty.server.ServerConnector.<init>(ServerConnector.java:94)
	at org.eclipse.jetty.runner.Runner.configure(Runner.java:398)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:566)
Usage: java [-Djetty.home=dir] -jar jetty-runner.jar [--help|--version] [ server opts] [[ context opts] context ...] 
Server opts:
 --version                           - display version and exit
 --log file                          - request log filename (with optional 'yyyy_mm_dd' wildcard
 --out file                          - info/warn/debug log filename (with optional 'yyyy_mm_dd' wildcard
 --host name|ip                      - interface to listen on (default is all interfaces)
 --port n                            - port to listen on (default 8080)
 --stop-port n                       - port to listen for stop command (or -DSTOP.PORT=n)
 --stop-key n                        - security string for stop command (required if --stop-port is present) (or -DSTOP.KEY=n)
 [--jar file]*n                      - each tuple specifies an extra jar to be added to the classloader
 [--lib dir]*n                       - each tuple specifies an extra directory of jars to be added to the classloader
 [--classes dir]*n                   - each tuple specifies an extra directory of classes to be added to the classloader
 --stats [unsecure|realm.properties] - enable stats gathering servlet context
 [--config file]*n                   - each tuple specifies the name of a jetty xml config file to apply (in the order defined)
Context opts:
 [[--path /path] context]*n          - WAR file, web app dir or context xml file, optionally with a context path

Process finished with exit code 1
```

**Comment by guikeller** [comment]
Hi @Joseph-Ryu 

It seems that you have something on your classpath that is causing this issue.

Note that some of your libs are required during compile time but not required during runtime.
They are not required during runtime because the servlet container provides them.

Some to look at - eg: 
/lib/**jetty/jsp-api-2.2.jar** 
/lib/**jetty/servlet-api-3.0.jar**
/lib/**jetty-io-9.4.1.v20170120.jar**
/lib/**jetty-util-9.4.1.v20170120.jar**
/lib/**spring-instrument-tomcat-4.1.1.RELEASE.jar**

It will be a bit of trial/error until you find which one is causing the error.

Good luck! Cheers

**Comment by Joseph-Ryu** [comment]
> Hi @Joseph-Ryu
> 
> It seems that you have something on your classpath that is causing this issue.
> 
> Note that some of your libs are required during compile time but not required during runtime.
> They are not required during runtime because the servlet container provides them.
> 
> Some to look at - eg:
> /lib/**jetty/jsp-api-2.2.jar**
> /lib/**jetty/servlet-api-3.0.jar**
> /lib/**jetty-io-9.4.1.v20170120.jar**
> /lib/**jetty-util-9.4.1.v20170120.jar**
> /lib/**spring-instrument-tomcat-4.1.1.RELEASE.jar**
> 
> It will be a bit of trial/error until you find which one is causing the error.
> 
> Good luck! Cheers

Hey guikeller,

Ty for the response.
Does that mean I would need to delete these files to make Jetty run?

**Comment by guikeller** [comment]
Hi @Joseph-Ryu,

It means that you don't need them in runtime but possibly in compile time.

As I said it will be trial and error until you find which one(s) have to be removed from the classpath so jetty starts and runs okay.
