### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid classes folder 

### ISSUE THREAD

**Issue by ms-clovis** [guikeller/jetty-runner#7]
Guelker,
      I am having the same issue as previous author. I am including another stacktrace in case it would helpl

Invalid classes folder: 
java.lang.IllegalArgumentException: Invalid classes folder: 
	at com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine.getClassesDirectory(JettyRunnerCommandLine.java:139)
	at com.github.guikeller.jettyrunner.runner.JettyRunnerCommandLine.createJavaParameters(JettyRunnerCommandLine.java:67)
	at com.intellij.execution.configurations.JavaCommandLineState.getJavaParameters(JavaCommandLineState.java:36)
	at com.intellij.execution.configurations.JavaCommandLineState.createCommandLine(JavaCommandLineState.java:54)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:44)
	at com.intellij.execution.configurations.JavaCommandLineState.startProcess(JavaCommandLineState.java:26)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:80)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.github.guikeller.jettyrunner.runner.JettyProgramRunner.doExecute(JettyProgramRunner.java:44)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$2.run(ExecutionManagerImpl.java:203)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:125)
	at com.intellij.execution.impl.ExecutionManagerImpl$1$1.run(ExecutionManagerImpl.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)

**Comment by guikeller** [comment]
Hi Ms Clovis,

The exception tells me that your "classes" folder is empty.
"java.lang.IllegalArgumentException: Invalid classes folder: "
Try creating a new configuration and running again.

If the same issue happens can you please provide a bit more info?
I will need a screenshot of your configuration and the version of IntelliJ that you're running.

Let me know how you go.

Cheers, 
Gui

**Comment by guikeller** [comment]
Closing the issue as I haven't heard back from the reporter.
I hope that uninstalling / installing the plugin and creating a new run conf has fixed the problem.
