### ISSUE TITLE
Intellij Idea - error in IDE caused by Jetty Runner

### ISSUE THREAD

**Issue by cvrdev** [guikeller/jetty-runner#78]
Hello, jetty runner plugin when opening ItelliJ community version (2021.3.1) an error.It occurs whenever Idea need to access the plugin. Running application works, only the error occurs. So it is not preventing the work but it is annoying. Here is the Stacktrace from Idea:

`com.intellij.diagnostic.PluginException: The default implementation of method 'getId' is deprecated, you need to override it in 'class com.github.guikeller.jettyrunner.conf.JettyRunnerConfigurationFactory'. The default implementation delegates to 'getName' which may be localized, but return value of this method must not depend on current localization. [Plugin: JettyRunner-GK]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.execution.configurations.ConfigurationFactory.getId(ConfigurationFactory.java:75)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1029)
	at com.intellij.execution.impl.RunManagerImpl.getFactory(RunManagerImpl.kt:1012)
	at com.intellij.execution.impl.RunnerAndConfigurationSettingsImpl.readExternal(RunnerAndConfigurationSettingsImpl.kt:204)
	at com.intellij.execution.impl.RCInArbitraryFileManager.loadChangedRunConfigsFromFile$intellij_platform_execution_impl(RCInArbitraryFileManager.kt:152)
	at com.intellij.execution.impl.RunManagerImpl.updateRunConfigsFromArbitraryFiles$intellij_platform_execution_impl(RunManagerImpl.kt:369)
	at com.intellij.execution.impl.RunConfigurationInArbitraryFileScanner$startSession$1$1.visitFile(RunConfigurationInArbitraryFileScanner.kt:37)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.applyScannersToFile(PushedFilePropertiesUpdaterImpl.java:170)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$collectIndexableFilesConcurrently$13(UnindexedFilesUpdater.java:436)
	at com.intellij.openapi.roots.impl.FileIndexBase.lambda$toContentIteratorEx$0(FileIndexBase.java:77)
	at com.intellij.openapi.roots.impl.FileIndexBase$1.visitFileEx(FileIndexBase.java:60)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:293)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:325)
	at com.intellij.openapi.roots.impl.FileIndexBase.iterateContentUnderDirectory(FileIndexBase.java:41)
	at com.intellij.openapi.roots.impl.ModuleFileIndexImpl.iterateContentUnderDirectory(ModuleFileIndexImpl.java:20)
	at com.intellij.util.indexing.roots.ModuleIndexableFilesIteratorImpl.iterateFiles(ModuleIndexableFilesIteratorImpl.kt:89)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$collectIndexableFilesConcurrently$14(UnindexedFilesUpdater.java:460)
	at com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl.lambda$invokeConcurrentlyIfPossible$22(PushedFilePropertiesUpdaterImpl.java:406)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.roots.impl.FilesScanExecutor.lambda$runOnAllThreads$0(FilesScanExecutor.java:37)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:246)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:32)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:225)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:214)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by guikeller** [comment]
Hi @cvrdev 

Thanks for reporting this, I will have a look into it soon.
It seems like a warning but I do agree with you, it is annoying.

Cheers, Gui

**Comment by guikeller** [comment]
While this would be nice to have it does not stop the plugin from running.  

Let's hope that someone else takes over and fixes this - see below.  
New Maintainer Wanted - https://github.com/guikeller/jetty-runner/issues/80
